Numpy - Numerical Python

Advantages of Numpy Arrays:
1. Allows several Mathematical Operations
2. Faster Operation

In [1]:
import numpy as np

In [2]:
# Numpy arr
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [3]:
np_array = np.array([1,2,3,4,5])
print(np_array) 
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [5]:
# Create a 1D array
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)
np_array.shape

[1 2 3 4 5]


(5,)

In [6]:
# Create a 2D array
np_array = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(np_array)
type(np_array)
np_array.shape

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


(2, 5)

In [7]:
c = np.array([1,2,3,4,5],dtype = float)
print(c)

[1. 2. 3. 4. 5.]


In [9]:
# Intial Placefolder in numpy arrays
x = np.zeros((4,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
y = np.ones((3,5))
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [11]:
# Array for particular value
z = np.full((3,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [12]:
#create Identity matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [13]:
# create a numpy array
b = np.random.random((3,4))
print(b)

[[0.80407897 0.81988195 0.38371772 0.51421617]
 [0.8231608  0.88118225 0.86855144 0.56305598]
 [0.6457064  0.38592581 0.7244561  0.56137917]]


In [14]:
c = np.random.randint(1,10,(3,4))
print(c)

[[3 7 8 3]
 [2 4 7 7]
 [7 1 3 6]]


In [15]:
# array of evenly spaced value
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [16]:
# Array of evenly space value
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [17]:
# convert the list to numpy array
list1 = [1,2,3,4,5]
np_array = np.asarray(list1)
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [18]:
# Analysing the numpy the array
f = np.random.randint(10,30,(5,5))

print(f)

[[23 25 19 22 20]
 [21 27 26 14 14]
 [20 24 21 20 12]
 [23 27 15 29 19]
 [12 11 26 14 14]]


In [19]:
# number of dimensions
print(f.shape)

(5, 5)


In [20]:
# number of dimension
print(f.ndim)

2


In [22]:
# number of element
print(f.size)

25


In [24]:
# Mathematical Operation on a np array
list1 = [1,3,3,4,4]
list2 = [1,3,4,4,3]
list3 = np.asarray(list1) + np.asarray(list2)
print(list3)

[2 6 7 8 7]


In [25]:
# transpose a numpy

a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
